# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirsttest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firsttest(self):
    self.driver.get("https://www.dfnpf.ru/")
    self.driver.set_window_size(1616, 876)
    self.driver.find_element(By.LINK_TEXT, "Личный кабинет").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("100000002")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("IJIp6Rpo")
    self.driver.find_element(By.CSS_SELECTOR, ".auth-form__submit > .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Оплата").click()
    self.driver.find_element(By.LINK_TEXT, "Профиль").click()
    element = self.driver.find_element(By.LINK_TEXT, "Мои заявления")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Мои заявления").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_outline").click()
    self.driver.close()
  
